language: node_js

script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build

after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
