const feedback = {
  LOAD_FEEDBACKS_ASYNC: 'LOAD_FEEDBACKS_ASYNC',
  LOAD_FEEDBACKS: 'LOAD_FEEDBACKS',
  DELETE_FEEDBACK_ASYNC: 'DELETE_FEEDBACK_ASYNC',
  DELETE_FEEDBACK: 'DELETE_FEEDBACK',
  MODEL_CHANGED: 'MODEL_CHANGED',
  LOAD_FEEDBACK_ASYNC: 'LOAD_FEEDBACK_ASYNC',
  LOAD_FEEDBACK: 'LOAD_FEEDBACK',
  SAVE_FEEDBACK_ASYNC: 'SAVE_FEEDBACK_ASYNC',
  ADD_FEEDBACK: 'ADD_FEEDBACK',
  UPDATE_FEEDBACK: 'UPDATE_FEEDBACK',
  CLOSE_SNACKBAR: 'CLOSE_SNACKBAR'
};

export default feedback;
