const feedback = {
  MODEL_CHANGED: 'MODEL_CHANGED',
  LOAD_FEEDBACK_ASYNC: 'LOAD_FEEDBACK_ASYNC',
  LOAD_FEEDBACK: 'LOAD_FEEDBACK',
  SAVE_FEEDBACK_ASYNC: 'SAVE_FEEDBACK_ASYNC',
  ADD_FEEDBACK: 'ADD_FEEDBACK',
  UPDATE_FEEDBACK: 'UPDATE_FEEDBACK'
};

export default feedback;
